version: "3"
services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    env_file:
      - ./postgres.env
    ports:
      - "5432:5432"
  exam:
    container_name: exam
    build:
      context: .
      args:
        - CONFIG_FILE=config.yaml
    restart: always
    env_file:
      - ./.env
    ports:
      - "80:5000"
    depends_on:
      - db
